### ISSUE TITLE
More General Makefiles

### ISSUE THREAD

**Issue by jbrindza** [UPenn-RoboCup/UPennalizers#10]
Most (if not all) of the makefiles assume the location of libraries and header files. This requires everyone to either install everything in the same place or edit the makefiles on a per computer basis.

I think an easy, good solution would be to use set environment variables for this e.g. WEBOTS_HOME,  LUA_LIB, LUA_INC, etc

If the person has them installed in a different directory then they can set these variables, otherwise it will use the assumed locations as we have before.

An external program such as CMake is also an option.

**Comment by yida** [comment]
Will that be a good idea to have kind of configure script to automatically check dependencies? CMake might be a good idea for dependencies, but since we mainly working on linux, cross platform seems to be useless
