### ISSUE TITLE
Darwin-OP Twisted with Upennalizer

### ISSUE THREAD

**Issue by meisamb** [UPenn-RoboCup/UPennalizers#17]
Hi
I got familiar with your project in github (UPennalizers) in past weeks.
I have tried to test it in my robot but there is big problem in sending data to correct actuators, because after running your codes the robot is being twisted.

in addition i could build and run the project in link below successfully:
http://www.seas.upenn.edu/~robocup/files/upenn_humanoid_1.1.zip

what's wrong with codes uploaded on github??? 

please help me to run UPennalizers project.
thanks a lot.

**Comment by SJ-YI** [comment]
Check the servo firmware version - old one uses 12 bit resolution and new one uses 14 bit resolution. 
Our code supports both versions. Open Config_OP_Robot.lua and uncomment the commented block for new firmware.

**Comment by meisamb** [comment]
Thanks for your quick reply.
i have applied this fix but nothing changed.
also "run_dcm.lua" returns 0 value for all joints..!

should i change this line too? :
servo.pid = 0; --old version of rx28M

**Comment by meisamb** [comment]
Thank you issue Solved!
