### ISSUE TITLE
unix.so dependency outside of Player

### ISSUE THREAD

**Issue by jbrindza** [UPenn-RoboCup/UPennalizers#6]
There needs to be a standard way for Lua to find the unix.so library (and others libraries) outside of Player directory. e.g. when running webots. It has been handled with links and with just copying the libraries into the WebotsController directory in the past.

It either needs to be standardized and made clear how it should be done or figure out a way of making sure Player/Lib can be found without needing unix.so first.

EDIT: I think os.getenv('PWD') should be enough. I know I tried this at some point in the past but I can't remember why I decided against it.

**Comment by yida** [comment]
tested on nao, op, webots
