### ISSUE TITLE
Stop tracking Config.lua

### ISSUE THREAD

**Issue by jbrindza** [UPenn-RoboCup/UPennalizers#7]
Remove the default Config.lua link and stop git from tracking it. This will avoid having users constantly switching the link because it changes for their setup. It should be set by the user and not part of the main system.

Currently the 'make setup_*' commands create a link to a default config file (e.g. Config_Nao.lua for the setup_nao, Config_Webots.lua for setup_webots). I don't think these should happen either. If someone is attempting to use a different config file they have to recreate the link everytime they recompile the libraries.

**Comment by yida** [comment]
tested on nao, op, webots, stop tracking Config.lua
