### ISSUE TITLE
Standardize Naming Schemes

### ISSUE THREAD

**Issue by jbrindza** [UPenn-RoboCup/UPennalizers#8]
It would be nice to have a standardized way to name new platforms. This would mainly be for indicating simulation vs the real robot platforms. Also, removing the ambiguous name 'Webots' for what is really the Nao Webots platform.

I propose just using camel-cased with the first letter capitalize. No spaces or underscores. If it is for a simulation the simulator name should be prepended.
e.g:
Nao
OP
WebotsNao
WebotsOP

Config Files should also follow a general format to make it easier to find the files needed:
Right now we have many different styles used for config names:
Config_OP_Camera_Webots.lua
Config_Webots_OP_Walk.lua
Config_Webots_Nao_Vision.lua
Config_Webots_Walk.lua

These should all be made in a standardized fashion:
Config_<Platform>_<Type>.lua

The previous examples would become: (respectively)
Config_WebotsOP_Camera.lua
Config_WebotsOP_Walk.lua
Config_WebotsNao_Vision.lua
Config_WebotsNo_Walk.lua

This will require a good amount of refactoring to change but I think the long term gains are worth it.

**Comment by jbrindza** [comment]
This should also be extended to the Platform specific libraries.

<Platform Name>LibraryName

e.g.
NaoKinematics
WebotsNaoKinematics
OPKinematics
WebotsOPKinematics

**Comment by yida** [comment]
Standard naming has been done in trunk, including platform library

**Comment by yida** [comment]
tested on Nao

**Comment by yida** [comment]
tested on op
